export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const IS_LOADING_CONVERSATIONS = 'IS_LOADING_CONVERSATIONS';
export const IS_LOADING_CONVERSATION = 'IS_LOADING_CONVERSATION';
export const SET_CONVERSATION = 'SET_CONVERSATION';
export const SET_REPLY = 'SET_REPLY';
export const ADD_TWEET_CONVERSATION = 'ADD_TWEET_CONVERSATION';
